id: P000614
initial_creation_type: ocr
source_metadata:
  id: bdr:W29894
  title: ལམ་རིམ། ༼དཔལ་ལྡན་ས་སྐྱ་པའི་དཔེ་ཚོགས།༽
  author: ''
  volumes:
    b75699de57154b26a1e90077f66ed21b:
      image_group_id: I5727
      title: ''
      volume_number: 1
      total_pages: 637
