id: P000614
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 2021-12-16 15:51:44.079344
source_metadata:
  id: bdr:W29894
  title: ལམ་རིམ། ༼དཔལ་ལྡན་ས་སྐྱ་པའི་དཔེ་ཚོགས།༽
  author: ''
  volumes:
    b75699de57154b26a1e90077f66ed21b:
      image_group_id: I5727
      title: ''
      volume_number: 1
      total_pages: 637
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
