id: I36340833
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T00:12:06+00:00'
last_modified: '2022-06-07T12:27:20.055018+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W29894
  title: ལམ་རིམ། ༼དཔལ་ལྡན་ས་སྐྱ་པའི་དཔེ་ཚོགས།༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '8389':
      image_group_id: I5727
      title: ''
      total_pages: 637
      order: 1
      base_file: 8389.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
